---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mexc-sniper-bot
    overwrite: true

permissions:
  - object: /home/ec2-user/mexc-sniper-bot
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/codedeploy/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/codedeploy/application_stop.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: scripts/codedeploy/validate_service.sh
      timeout: 120
      runas: ec2-user
